import streamlit as st
import pandas as pd
import altair as alt

timestamp =  ["0:02", "0:05", "0:12", "0:17", "0:20", "0:23", "0:27", "0:30", "0:32", "0:35",
                  "0:37", "0:40", "0:43", "0:49", "0:52", "0:56", "0:58", "1:01", "1:04", "1:07",
                  "1:10", "1:14", "1:17", "1:21", "1:23", "1:29", "1:32", "1:34", "1:37", "1:40",
                  "1:44", "1:48", "1:51", "1:54", "1:59", "2:02", "2:05", "2:08", "2:10", "2:14",
                  "2:17", "2:19", "2:22", "2:25", "2:29", "2:33", "2:36", "2:38", "2:43", "2:47",
                  "2:51", "2:54", "2:57", "2:59", "3:02", "3:05", "3:07", "3:10", "3:13", "3:17",
                  "3:20", "3:22", "3:25", "3:28", "3:32", "3:36", "3:39", "3:43", "3:49", "3:52",
                  "3:57", "4:00", "4:03", "4:06", "4:09", "4:12", "4:15", "4:18", "4:20", "4:23",
                  "4:26", "4:30", "4:33", "4:35", "4:38", "4:41", "4:46", "4:49", "4:52", "4:55",
                          "4:57", "5:00", "5:03", "5:09", "5:18", "5:20",
                  "5:24",
                  "5:28",
                  "5:37",
                  "5:40",
                  "5:46",
                  "5:56",
                  "5:59",
                  "6:09",
                  "6:12",
                  "6:18",
                  "6:27",
                  "6:41",
                  "6:59",
                  "7:05",
                  "7:08",
                  "7:19",
                  "7:27",
                  "7:42",
                  "7:47",
                  "8:00",
                  "8:08",
                  "8:24",
                  "8:39",
                  "8:44",
                  "8:57",
                  "9:05",
                  "9:07",
                  "9:21",
                  "9:28",
                  "9:31",
                  "9:34",
                  "9:38",
                  "9:51",
                  "9:53",
                  "9:56",
                  "9:59",
                  "10:02",
                  "10:05",
                  "10:15",
                  "10:18",
                  "10:24",
                  "10:27",
                  "10:30",
                  "10:33",
                  "10:36",
                  "10:39",
                  "10:49",
                  "10:58",
                  "11:02",
                  "11:05",
                  "11:15",
                  "11:19",
                  "11:22",
                  "11:25",
                  "11:28",
                  "11:32",
                  "11:37",
                  "11:40",
                  "11:50",
                  "11:53",
                  "11:57",
                  "12:00",
                  "12:05",
                  "12:08",
                  "12:11",
                  "12:14",
                  "12:17",
                  "12:20",
                  "12:24",
                  "12:31",
                  "12:33",
                  "12:36",
                  "12:39",
                  "12:48",
                  "12:51",
                  "12:54",
                  "12:57",
                  "13:00",
                  "13:04",
                  "13:07",
                  "13:15",
                  "13:19",
                  "13:25",
                  "13:28",
                  "13:31",
                  "13:35",
                  "13:38",
                  "13:42",
                  "13:47",
                  "13:54",
                  "13:58",
                  "14:00",
                  "14:04",
                  "14:07",
                  "14:10",
                  "14:13",
                  "14:21",
                  "14:24",
                  "14:27",
                  "14:31",
                  "14:34",
                  "14:36",
                  "14:39",
                  "14:44",
                  "14:53",
                  "14:56",
                  "14:59",
                  "15:02",
                  "15:05",
                  "15:08",
                  "15:18",
                  "15:21",
                  "15:24",
                  "15:26",
                  "15:29",
                  "15:32",
                  "15:35",
                  "15:39",
                  "15:41",
                  "15:50",
                  "15:57",
                  "16:00",
                  "16:10",
                  "16:12",
                  "16:16",
                  "16:19",
                  "16:22",
                  "16:28",
                  "16:31",
                  "16:33",
                  "16:40",
                  "16:42",
                  "16:44",
                  "16:47",
                  "16:50",
                  "16:53",
                  "16:56",
                  "17:00",
                  "17:06",
                  "17:09",
                  "17:12",
                  "17:18",
                  "17:21",
                  "17:27",
                  "17:31",
                  "17:35",
                  "17:38",
                  "17:43",
                  "17:47",
                  "17:50",
                  "17:52",
                  "18:00",
                  "18:05", "18:11", "18:16", "18:19", "18:21", "18:34", "18:36", "18:44", "18:46", "18:49", "18:59", "19:02", "19:05", "19:07", "19:10", "19:13", "19:16", "19:20", "19:23", "19:26", "19:31", "19:35", "19:43", "19:46", "19:49", "19:57", "20:00", "20:04", "20:06", "20:12", "20:15", "20:19", "20:21", "20:24", "20:27", "20:30", "20:33", "20:45", "20:47", "21:09",
                  "21:16", "21:22", "21:25", "21:28", "21:31", "21:39", "21:42", "21:46", "21:49", "21:56", "21:59", "22:02", "22:05", "22:08", "22:14", "22:17", "22:20", "22:23", "22:26", "22:30", "22:39", "22:43", "22:46", "22:49", "22:56", "23:00", "23:04", "23:07", "23:10", "23:13", "23:16", "23:19", "23:21", "23:30", "23:32", "23:40", "23:43", "23:46", "23:50", "23:58"
                  ]

artist = ["Taylor Swift",
          "Thuy",
          "Lil Nas X",
          "Lizzo",
          "Joji",
          "The Weeknd",
          "JVKE",
          "Lil Uzi Vert",
          "(G)I-DLE",
          "Harry Styles",
          "Sabrina Carpenter",
          "Doja Cat",
          "Rema, Selena Gomez",
          "Sam Smith",
          "Lady Gaga",
          "Meghan Trainor",
          "SZA",
          "Steve Lacy",
          "Jax",
          "Taylor Swift",
          "Tom Odell",
          "Harry Styles",
          "Metro Boomin, The Weeknd, 21 Savage",
          "Nicki Minaj",
          "Tate McRae",
          "Nicky Youre",
          "Lil Nas X",
          "Stephen Sanchez",
          "Chris Brown",
          "Post Malone",
          "Oliver Tree x Robin Schulz",
          "Harry Styles",
          "SZA",
          "Beyonce",
          "Loud Luxury feat. KIDDO",
          "Lizzo",
          "Raye, 070 Shake",
          "Sam Smith",
          "Joji",
          "JVKE",
          "SZA",
          "Doja Cat",
          "Lewis Capaldi",
          "Taylor Swift",
          "Rema, Selena Gomez",
          "The Neighborhood",
          "Meghan Trainor",
          "Renee' Rapp",
          "Tyga, Jhené Aiko, Pop Smoke",
          "The Weeknd",
          "(G)I-DLE",
          "Steve Lacy",
          "Lil Uzi Vert",
          "Harry Styles",
          "Sabrina Carpenter",
          "Harry Styles",
          "Rosa Linn",
          "Nicki Minaj",
          "Metro Boomin, The Weeknd, 21 Savage",
          "Stephen Sanchez",
          "The Driver Era",
          "Sam Smith",
          "Lil Nas X",
          "Tom Odell",
          "Beyonce",
          "charlieonnafriday",
          "Taylor Swift",
          "Thuy",
          "Chris Brown",
          "Taylor Swift",
          "Raye, 070 Shake",
          "Lizzo",
          "Tate McRae",
          "Post Malone",
          "Joji",
          "JVKE",
          "SZA",
          "Doja Cat",
          "Rihanna",
          "Harry Styles",
          "Rema, Selena Gomez",
          "(G)I-DLE",
          "Meghan Trainor",
          "Tyga, Jhené Aiko, Pop Smoke",
          "Sam Smith",
          "Lady Gaga",
          "Taylor Swift",
          "Jax",
          "Steve Lacy",
          "Lil Uzi Vert",
          "Bruno Mars",
          "Harry Styles",
          "Renee' Rapp",
          "Oliver Tree x Robin Schulz",
          "Nicki Minaj",
          "Raye, 070 Shake",
          "The Weeknd",
          "Metro Boomin, The Weeknd, 21 Savage",
          "Sabrina Carpenter",
          "Stephen Sanchez",
          "Harry Styles",
          "Sam Smith",
          "Beyonce",
          "Kelly Clarkson",
          "Taylor Swift",
          "Jack Harlow",
          "Taylor Swift",
          "Doja Cat",
          "JVKE",
          "Harry Styles",
          "Steve Lacy",
          "The Weeknd/Daft Punk",
          "Meghan Trainor",
          "Sam Smith",
          "Taylor Swift",
          "Lil Nas X",
          "Nicki Minaj",
          "Doja Cat",
          "Harry Styles",
          "The Weeknd",
          "Ariana Grande",
          "Sam Smith",
          "Justin Bieber",
          "Jack Harlow",
          "Taylor Swift",
          "Lizzo",
          "Sia",
          "Doja Cat",
          "Nick Jonas",
          "Post Malone",
          "JVKE",
          "Harry Styles",
          "The Chainsmokers/Daya",
          "Metro Boomin, The Weeknd, 21 Savage",
          "Meghan Trainor",
          "Sam Smith",
          "Steve Lacy",
          "Calvin Harris / Dua Lipa",
          "Harry Styles",
          "Doja Cat",
          "Taylor Swift",
          "Raye, 070 Shake",
          "Nicki Minaj",
          "The Weeknd",
          "Shawn Mendes",
          "SZA",
          "Stephen Sanchez",
          "Rihanna/Drake",
          "Harry Styles",
          "Nicky Youre, dazy",
          "Beyonce",
          "Sam Smith",
          "Taylor Swift",
          "Rema, Selena Gomez",
          "Lizzo",
          "Taylor Swift",
          "FloRida",
          "JVKE",
          "Jax",
          "Doja Cat",
          "One Republic",
          "Metro Boomin, The Weeknd, 21 Savage",
          "Post Malone",
          "Wiz Khalifa",
          "Meghan Trainor",
          "Lil Nas X",
          "Harry Styles",
          "Pitbull/Ne-Yo",
          "Lady Gaga",
          "Steve Lacy",
          "Sam Smith",
          "Rihanna",
          "Harry Styles",
          "Taylor Swift",
          "The Weeknd",
          "SZA",
          "Justin Bieber",
          "Nicki Minaj",
          "Jack Harlow",
          "Stephen Sanchez",
          "The Weeknd",
          "Sia",
          "Beyonce",
          "Niall Horan",
          "Metro Boomin, The Weeknd, 21 Savage",
          "Taylor Swift",
          "Harry Styles",
          "Drake",
          "Lizzo",
          "Sam Smith",
          "The Neighborhood",
          "JVKE",
          "Benny Blanco / Khalid / Halsey",
          "Taylor Swift",
          "Ed Sheeran",
          "Doja Cat",
          "Ariana Grande",
          "Meghan Trainor",
          "Latto x Mariah Carey",
          "SZA",
          "Steve Lacy",
          "Post Malone",
          "Taylor Swift",
          "Harry Styles",
          "Harry Styles",
          "Metro Boomin, The Weeknd, 21 Savage",
          "Justin Bieber",
          "Nicki Minaj",
          "Sam Smith",
          "Doja Cat",
          "Stephen Sanchez",
          "Taylor Swift",
          "Beyonce",
          "Lil Nas X",
          "Raye, 070 Shake",
          "Taylor Swift",
          "Eminem ft. Rihanna",
          "Lizzo",
          "Glass Animals",
          "The Weeknd",
          "JVKE",
          "Avicii",
          "Doja Cat",
          "Jack Harlow",
          "Meghan Trainor",
          "Luis Fonsi/Justin Bieber/Daddy Yankee",
          "Lady Gaga",
          "Sam Smith",
          "One Republic",
          "Steve Lacy",
          "Taylor Swift",
          "Metro Boomin, The Weeknd, 21 Savage",
          "Ed Sheeran",
          "Harry Styles",
          "The Neighborhood",
          "Nicki Minaj",
          "SZA",
          "Stephen Sanchez",
          "Post Malone",
          "Beyonce",
          "Rema, Selena Gomez",
          "Harry Styles",
          "Macklemore",
          "Taylor Swift",
          "Latto x Mariah Carey",
          "Sam Smith",
          "Jax",
          "Lizzo",
          "Taylor Swift",
          "JVKE",
          "Doja Cat",
          "Meghan Trainor",
          "Metro Boomin, The Weeknd, 21 Savage",
          "Nicky Youre, dazy",
          "Raye, 070 Shake",
          "Harry Styles",
          "Steve Lacy",
          "SZA",
          "Harry Styles",
          "Jack Harlow",
          "Sam Smith",
          "SZA",
          "Doja Cat",
          "Taylor Swift",
          "Rema, Selena Gomez",
          "The Weeknd",
          "Stephen Sanchez",
          "Nicki Minaj",
          "Beyonce",
          "Daniel Seavey",
          "Post Malone",
          "The Neighborhood",
          "Lil Uzi Vert",
          "Taylor Swift",
          "Baby Bash",
          "Harry Styles",
          "Metro Boomin, The Weeknd, 21 Savage",
          "Sam Smith",
          "Lizzo",
          "Sabrina Carpenter",
          "Young Thug",
          "JVKE",
          "Doja Cat",
          "Taylor Swift",
          "SZA",
          "Lil Nas X",
          "Jax",
          "Beyonce",
          "JVKE",
          "Metro Boomin, The Weeknd, 21 Savage",
          "Meghan Trainor",
          "Steve Lacy",
          "Harry Styles",
          "Tyga, Jhené Aiko, Pop Smoke",
          "The Weeknd",
          "Sam Smith",
          "Nezza",
          "Harry Styles",
          "Latto x Mariah Carey",
          "Taylor Swift",
          "Drake, 21 Savage",
          "Stephen Sanchez",
          "SZA",
          "Nicki Minaj",
          "Dua Lipa",
          "Post Malone",
          "Beyonce",
          "SZA",
          "Taylor Swift",
          "Jack Harlow",
          "Harry Styles",
          "Raye, 070 Shake",
          "Lizzo",
          "Lady Gaga",
          "Sam Smith",
          "Metro Boomin, The Weeknd, 21 Savage",
          "JVKE",
          "Jack Harlow",
          "Taylor Swift",
          "Lil Uzi Vert",
          "Doja Cat",
          "Meghan Trainor",
          "Sabrina Carpenter",
          "Steve Lacy",
          "The Neighborhood",
          "The Weeknd",
          "Tyga, Jhené Aiko, Pop Smoke",
          "Thuy",
    
]
songs = [
        "Lavender Haze",
        "Girls Like Me Don't Cry",
        "Star Walkin",
        "About Damn Time",
        "Die For You",
        "Die For You",
        "Golden Hour",
        "Just Wanna Rock",
        "Nxde",
        "As It Was",
        "Nonsense",
        "Vegas",
        "Calm Down",
        "Unholy (feat. Kim Petras)",
        "Bloody Mary",
        "Made You Look",
        "Kill Bill",
        "Bad Habit",
        "Victoria's Secret",
        "Anti-Hero",
        "Another Love",
        "Late Night Talking",
        "Creepin'",
        "Super Freaky Girl",
        "Uh Oh",
        "Eyes On You",
        "That's What I Want",
        "Until I Found You",
        "Under The Influence",
        "I Like You (A Happier Song) feat. Doja Cat",
        "Miss You",
        "As It Was",
        "Nobody Gets Me",
        "Cuff It",
        "These Nights",
        "About Damn Time",
        "Escapism",
        "Unholy (feat. Kim Petras)",
        "Die For You",
        "Golden Hour",
        "Kill Bill",
        "Vegas",
        "Forget Me",
        "Anti-Hero",
        "Calm Down",
        "Sweater Weather",
        "Made You Look",
        "Too Well",
        "Sunshine",
        "Die For You",
        "Nxde",
        "Bad Habit",
        "Just Wanna Rock",
        "Late Night Talking",
        "Nonsense",
        "As It Was",
        "SNAP",
        "Super Freaky Girl",
        "Creepin'",
        "Until I Found You",
        "Malibu",
        "Unholy (feat. Kim Petras)",
        "Star Walkin",
        "Another Love",
        "Cuff It",
        "Enough",
        "Anti-Hero",
        "Girls Like Me Don't Cry",
        "Under The Influence",
        "Lavender Haze",
        "Escapism",
        "About Damn Time",
        "Uh Oh",
        "I Like You (A Happier Song) feat. Doja Cat",
        "Die For You",
        "Golden Hour",
        "Kill Bill",
        "Vegas",
        "Lift Me Up",
        "As It Was",
        "Calm Down",
        "Nxde",
        "Made You Look",
        "Sunshine",
        "Unholy (feat. Kim Petras)",
        "Bloody Mary",
        "Anti-Hero",
        "Victoria's Secret",
        "Bad Habit",
        "Just Wanna Rock",
        "24K Magic",
        "Late Night Talking",
        "Too Well",
        "Miss You",
        "Super Freaky Girl",
        "Escapism",
        "Die For You",
        "Creepin'",
        "Nonsense",
        "Until I Found You",
        "As It Was",
        "Unholy (feat. Kim Petras)",
        "Cuff It",
        "Since You Been Gone",
        "Lavender Haze",
        "First Class",
        "Anti-Hero",
        "Vegas",
        "Golden Hour",
        "As It Was",
        "Bad Habit",
        "STARBOY",
        "Made You Look",
        "Unholy (feat. Kim Petras)",
        "Anti-Hero",
        "That's What I Want",
        "Super Freaky Girl",
        "Say So",
        "As It Was",
        "Die For You",
        "One Last Time",
        "Unholy (feat. Kim Petras)",
        "Peaches f. Daniel Caesar and Giveon",
        "First Class",
        "Anti-Hero",
        "About Damn Time",
        "Unstoppable",
        "Vegas",
        "Jealous",
        "I Like You (A Happier Song) feat. Doja Cat",
        "Golden Hour",
        "As It Was",
        "Don't Let Me Down",
        "Creepin'",
        "Made You Look",
        "Unholy (feat. Kim Petras)",
        "Bad Habit",
        "One Kiss",
        "Late Night Talking",
        "Woman",
        "Anti-Hero",
        "Escapism",
        "Super Freaky Girl",
        "Die For You",
        "There's Nothing Holding Me Back",
        "Nobody Gets Me",
        "Until I Found You",
        "Work",
        "As It Was",
        "Sunroof",
        "Cuff It",
        "Unholy (feat. Kim Petras)",
        "Lavender Haze",
        "Calm Down",
        "About Damn Time",
        "Anti-Hero",
        "Good Feeling",
        "Golden Hour",
        "Victoria's Secret",
        "Vegas",
        "I Ain't Worried",
        "Creepin'",
        "I Like You (A Happier Song) feat. Doja Cat",
        "See You Again ft. Charlie Puth",
        "Made You Look",
        "That's What I Want",
        "As It Was",
        "Give Me Everything",
        "Bloody Mary",
        "Bad Habit",
        "Unholy (feat. Kim Petras)",
        "Diamonds",
        "Late Night Talking",
        "Anti-Hero",
        "Blinding Lights",
        "Kill Bill",
        "Love Yourself",
        "Super Freaky Girl",
        "First Class",
        "Until I Found You",
        "Die For You",
        "Unstoppable",
        "Cuff It",
        "Slow Hands",
        "Creepin'",
        "Lavender Haze",
        "As It Was",
        "Hotline Bling",
        "About Damn Time",
        "Unholy (feat. Kim Petras)",
        "Sweater Weather",
        "Golden Hour",
        "Eastside",
        "Anti-Hero",
        "Shivers",
        "Vegas",
        "The Way",
        "Made You Look",
        "Big Energy Remix",
        "Nobody Gets Me",
        "Bad Habit",
        "I Like You (A Happier Song) feat. Doja Cat",
        "Style",
        "Late Night Talking",
        "As It Was",
        "Creepin'",
        "Ghost",
        "Super Freaky Girl",
        "Unholy (feat. Kim Petras)",
        "Woman",
        "Until I Found You",
        "Anti-Hero",
        "Cuff It",
        "That's What I Want",
        "Escapism",
        "Lavender Haze",
        "The Monster",
        "About Damn Time",
        "Heat Waves",
        "Die For You",
        "Golden Hour",
        "Wake Me Up",
        "Vegas",
        "First Class",
        "Made You Look",
        "Despacito Remix",
        "Bloody Mary",
        "Unholy (feat. Kim Petras)",
        "I Ain't Worried",
        "Bad Habit",
        "Anti-Hero",
        "Creepin'",
        "Bad Habits",
        "Late Night Talking",
        "Sweater Weather",
        "Super Freaky Girl",
        "Kill Bill",
        "Until I Found You",
        "I Like You (A Happier Song) feat. Doja Cat",
        "Cuff It",
        "Calm Down",
        "As It Was",
        "Can't Hold Us",
        "Lavender Haze",
        "Big Energy Remix",
        "Unholy (feat. Kim Petras)",
        "Victoria's Secret",
        "About Damn Time",
        "Anti-Hero",
        "Golden Hour",
        "Vegas",
        "Made You Look",
        "Creepin'",
        "Sunroof",
        "Escapism",
        "As It Was",
        "Bad Habit",
        "Nobody Gets Me",
        "Late Night Talking",
        "First Class",
        "Unholy (feat. Kim Petras)",
        "Kill Bill",
        "Woman",
        "Anti-Hero",
        "Calm Down",
        "Heartless",
        "Until I Found You",
        "Super Freaky Girl",
        "Cuff It",
        "Runaway",
        "I Like You (A Happier Song) feat. Doja Cat",
        "Sweater Weather",
        "Just Wanna Rock",
        "Lavender Haze",
        "Suga Suga",
        "As It Was",
        "Creepin'",
        "Unholy (feat. Kim Petras)",
        "About Damn Time",
        "Nonsense",
        "Go Crazy",
        "Golden Hour",
        "Vegas",
        "Anti-Hero",
        "Nobody Gets Me",
        "That's What I Want",
        "Victoria's Secret",
        "Cuff It",
        "Golden Hour",
        "Creepin'",
        "Made You Look",
        "Bad Habit",
        "As It Was",
        "Sunshine",
        "Die For You",
        "Unholy (feat. Kim Petras)",
        "Poison",
        "Late Night Talking",
        "Big Energy Remix",
        "Anti-Hero",
        "Rich Flex",
        "Until I Found You",
        "Nobody Gets Me",
        "Super Freaky Girl",
        "Levitating",
        "I Like You (A Happier Song) feat. Doja Cat",
        "Cuff It",
        "Kill Bill",
        "Lavender Haze",
        "Industry Baby",
        "As It Was",
        "Escapism",
        "About Damn Time",
        "Bloody Mary",
        "Unholy (feat. Kim Petras)",
        "Creepin'",
        "Golden Hour",
        "First Class",
        "Anti-Hero",
        "Just Wanna Rock",
        "Vegas",
        "Made You Look",
        "Nonsense",
        "Bad Habit",
        "Sweater Weather",
        "Die For You",
        "Sunshine",
        "Girls Like Me Don't Cry",]


data = pd.DataFrame({'Song': songs, 'Artist': artist, 'Timestamp': timestamp})



def app():
    st.write("Made with 💖 by Krish Rastogi")

    st.title("99.7 NOW -- Visualized")
    st.subheader('Your favorite songs & artists')
    
    freq = data.groupby(['Song', 'Artist']).size().reset_index(name='count')
    chart = alt.Chart(freq).mark_bar().encode(
    x='count',
    y=alt.Y('Song', sort='-x'),
    color='Artist')
    st.altair_chart(chart, use_container_width=True)
    
    st.write('Data Table')
    st.dataframe(data)

    st.write('Song Timestamp over Time')
    st.line_chart(data['Song'])

app()
